# Use LTS 22.39 which corresponds to GHC 9.6.6 (recent stable version)
resolver: lts-22.39

packages:
- '.'
# - core/
# - accelerate/

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []

ghc-options: {} 
  # "*" : -w -Wno-missing-signatures # -fprint-potential-instances
  # "*" : -Wno-missing-signatures -Wno-name-shadowing -Wno-unused-imports # -fprint-potential-instances
